#
# Makefile for misc devices that really don't fit anywhere else.
#


obj-y += s6d7aa6x01_hsd_hd720_6p0_helitech_x6068_blu.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc


